<?php

return [
    'K01' => ['file' => 'k01.png', 'source' => 'https://www.kahfeveryday.com/product/kahf-oil-and-acne-care-face-wash/'],
    'K02' => ['file' => 'k02.jpg', 'source' => 'https://www.watsons.co.id/id/kahf-skin-energizing-and-brightening-face-wash-100ml/p/BP_18040'],
    'K03' => ['file' => 'k03.png', 'source' => 'https://www.watsons.co.id/id/kahf-acne-and-pore-cleanse-scrub-face-wash-100-ml/p/BP_42102'],
    'K04' => ['file' => 'k04.png', 'source' => 'https://denusastore.com/product/kahf-face-wash-brightening-and-dark-spot-scrub-100ml/'],
    'K05' => ['file' => 'k05.jpg', 'source' => 'https://www.watsons.co.id/en/kahf-triple-action-oil-and-comede-defense-face-wash-100-ml/p/BP_27218'],
    'K06' => ['file' => 'k06.png', 'source' => 'https://www.watsons.co.id/id/kahf-acne-care-amino-gel-face-wash-100ml/p/BP_59342'],
    'K07' => ['file' => 'k07.png', 'source' => 'https://www.kahfeveryday.com/product/kahf-bright-revitalizing-aminogel-face-wash/'],
    'M01' => ['file' => 'm01.webp', 'source' => 'https://www.mandjur.co.id/products/ms-glow-men-energizer-facial-wash-100-ml'],
    'M02' => ['file' => 'm02.png', 'source' => 'https://www.astronauts.id/p/ms-glow-for-men-ultra-bright-facial-wash-100ml-45422'],
    'M03' => ['file' => 'm03.png', 'source' => 'https://www.astronauts.id/p/ms-glow-for-men-hydra-boost-facial-wash-100ml-45421'],
    'M04' => ['file' => 'm04.png', 'source' => 'https://www.astronauts.id/p/ms-glow-for-men-acnotion-facial-wash-100ml'],
    'G01' => ['file' => 'g01.jpg', 'source' => 'https://www.watsons.co.id/id/garnier-men-acno-fight-foam-6-in-1-anti-acne-100ml/p/BP_32839'],
    'G02' => ['file' => 'g02.png', 'source' => 'https://www.garnier.co.id/tentang-brands/garnier-men/acno-fight/acnofight-wasabi-brightening-foam-facial-cleanser'],
    'G03' => ['file' => 'g03.png', 'source' => 'https://www.garnier.co.id/tentang-brands/garnier-men/oil-control/oil-control-anti-shine-brightening-cooling-foam'],
    'G04' => ['file' => 'g04.jpg', 'source' => 'https://www.garnier.co.id/tentang-brands/garnier-men/oil-control/oil-control-super-duo-foam'],
    'G05' => ['file' => 'g05.jpg', 'source' => 'https://www.garnier.co.id/tentang-brands/garnier-men/oil-control/oil-control-matcha-deep-clean-foaming-gel'],
    'G06' => ['file' => 'g06.jpg', 'source' => 'https://www.watsons.co.id/id/garnier-men-turbo-light-oil-control-3-1-charcoal-100ml/p/BP_35082'],
    'G07' => ['file' => 'g07.jpg', 'source' => 'https://www.garnier.co.id/tentang-brands/garnier-men/oil-control/oil-control-icy-scrub'],
    'G08' => ['file' => 'g08.webp', 'source' => 'https://www.garnier.co.id/tentang-brands/garnier-men/turbobright/turbobright-super-duo-foam'],
    'G09' => ['file' => 'g09.jpg', 'source' => 'https://www.garnier.co.id/tentang-brands/garnier-men/turbobright/turbobright-shaving-cleansing-brightening-foam'],
    'N01' => ['file' => 'n01.webp', 'source' => 'https://www.nivea.co.id/produk/nivea-men-deep-acne-attack-scrub-mud-facial-foam-100ml-89997770172930048.html'],
    'N02' => ['file' => 'n02.png', 'source' => 'https://www.nivea.co.id/produk/nivea-men-bright-oil-clear-pore-minimizing-scrub-100ml-89997770029540048.html'],
    'N03' => ['file' => 'n03.png', 'source' => 'https://www.nivea.co.id/produk/nivea-men-extra-bright-facial-foam-50ml-89997778883500048.html'],
    'N04' => ['file' => 'n04.png', 'source' => 'https://www.nivea.co.id/produk/nivea-men-acne-oil-clear-acne-defense-foam-89997778883810048.html'],
    'N05' => ['file' => 'n05.png', 'source' => 'https://www.nivea.co.id/produk/nivea-men-bright-oil-clear-anti-shinepluspurify-mud-foam-100ml-40058086948220048.html'],
    'N06' => ['file' => 'n06.png', 'source' => 'https://www.nivea.co.id/produk/nivea-men-extra-bright-mud-foam-100ml-89997770017110048.html'],
    'N07' => ['file' => 'n07.png', 'source' => 'https://www.nivea.co.id/produk/nivea-men-extra-bright-facial-foam-100ml-89997778883670048.html'],
    'N08' => ['file' => 'n08.png', 'source' => 'https://www.nivea.co.id/produk/nivea-men-bright-oil-clear-pore-minimizing-foam-100ml-89997770001890048.html'],
    'B01' => ['file' => 'b01.jpg', 'source' => 'https://www.kao.com/id/id/products/mensbiore/mbi_bright_expert_00/'],
    'B02' => ['file' => 'b02.jpg', 'source' => 'https://www.kao.com/id/id/products/mensbiore/mbi_nonscrub_bright_00/'],
    'B03' => ['file' => 'b03.jpg', 'source' => 'https://www.kao.com/id/id/products/mensbiore/mbi_nonscrub_acne_00/'],
    'B04' => ['file' => 'b04.jpg', 'source' => 'https://www.kao.com/id/id/products/mensbiore/mbi_bright_oilclear_00/'],
    'B05' => ['file' => 'b05.jpg', 'source' => 'https://www.kao.com/id/id/products/mensbiore/mbi_doublescrub_white_00/'],
    'B06' => ['file' => 'b06.jpg', 'source' => 'https://www.kao.com/id/id/products/mensbiore/mbi_doublescrub_cool_00/'],
    'B07' => ['file' => 'b07.jpg', 'source' => 'https://www.kao.com/id/id/products/mensbiore/mbi_doublescrub_fresh_00/'],
    'B08' => ['file' => 'b08.jpg', 'source' => 'https://www.kao.com/id/id/products/mensbiore/mbi_doublescrub_antibacterior_00/'],
    'B03N' => ['file' => 'b03n.webp', 'source' => 'https://indonesiabiore.com/mensbiore/product/acne-bright-care'],
];
